// <auto-generated />
namespace Pohui.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DbMigrationsConfigurationAutomaticMigrationsEnabledtrue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbMigrationsConfigurationAutomaticMigrationsEnabledtrue));
        
        string IMigrationMetadata.Id
        {
            get { return "201311212048160_DbMigrationsConfiguration.AutomaticMigrationsEnabled=true"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
